### ISSUE TITLE
Consider relaxing dependency requirements

### ISSUE THREAD

**Issue by markns** [infobip-community/infobip-api-python-sdk#82]
Hi, could you consider relaxing the fixed dependency requirements?

I'm trying to build an airbyte source connector for infobip, but I run into the following problem:

```
ERROR: Cannot install -r requirements.txt (line 1), connector-acceptance-test and source-infobip because these package versions have conflicting dependencies.

The conflict is caused by:
    connector-acceptance-test 0.0.0 depends on pydantic~=1.6
    airbyte-cdk 0.2.0 depends on pydantic~=1.9.2
    infobip-api-python-sdk 5.0.0 depends on pydantic==1.9.0
```

**Comment by strosek** [comment]
Hi Mark. We updated the library (to v5.0.1) to use the compatibility operator instead of the '=='. However, we needed to update Pydantic to v1.10.8 specifically because that enables Python 3.11 compatibilty. Could you see if this change helps?

**Comment by markns** [comment]
Hi @strosek, I decided to take a different approach with the data ingestion (infobip reports->s3->airbyte s3 connector->db), so I'm afraid I'm not in a position to test this anymore. Thanks for the response anyway.
